### ISSUE TITLE
 Symbol's value as variable is void: {

### ISSUE THREAD

**Issue by ghost** [nice/themeforge#2]
Warning (initialization): An error occurred while loading ‘/home/perrierjouet/.emacs.d/init.el’:

Symbol's value as variable is void: {

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging

**Comment by nice** [comment]
@wereket can you share the input JSON and the generated theme output here.
There shouldn't have been any curly braces in the generated theme.

**Comment by ghost** [comment]
everything works perfect.
I wish I was elon musk... you deserve 1 000 $US or more  for this package
